### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by albertotn** [begriffs/groupthink#14]
Hi! I've tried to build groupthink today on my system:

windows 8
npm 2.15.1
bower 1.7.9
grunt-cli v1.2.0
grunt v1.0.1

and get following error

1 error in 3 files
Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! groupthink@0.0.9 postinstall: `bower cache clean && bower install && gr
unt precompile`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the groupthink@0.0.9 postinstall script 'bower cache clean &&
 bower install && grunt precompile'.
npm ERR! This is most likely a problem with the groupthink package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower cache clean && bower install && grunt precompile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs groupthink
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls groupthink
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\temp\groupthink\npm-debug.log

[npm-debug.zip](https://github.com/begriffs/groupthink/files/334863/npm-debug.zip)

**Comment by begriffs** [comment]
Thanks for reporting this. It should be fixed now.
